apiVersion: v1
kind: Service
metadata:
  name: clinica-service
  namespace: default
  labels:
    app: clinica
spec:
  selector:
    app: clinica
  ports:
  - name: http
    port: 9091
    targetPort: 9091
    protocol: TCP
  type: ClusterIP