---
# tasks file for common
- name: create devops group
  gid: 2010
  group:
    name: devops
    state: present
    
- name: create devops user with admin privileges and assign to devops group
  become: true
  user: 
    name: "devops"
    password: "devops"
    comment: "DevOps User"
    uid: 2001
    group: devops
    groups: sudo, devops
    
- name: install other basic packages
  apt: 
    pkg:
      - tree
      - curl
      - htop 
      - sudo
      - git
